Update

diff --git a/push b/push
--- a/push
+++ b/push
@@ -1,18 +1,23 @@
 #!/usr/bin/env bash
 set -e
 
-git checkout dev
+current_branch=$(git rev-parse --abbrev-ref HEAD)
+if [ "$current_branch" != "dev" ]; then
+    echo "Error: You are not on the correct branch. Aborting."
+    exit 1
+fi
+
 git add -A
 
 if [[ -z $1 ]]; then
-    git commit -m "Update"
+    git commit -m Update
 else
     git commit -m "$1"
 fi
 
 git push origin dev
 
-git checkout master
+git switch master
 git merge -Xtheirs dev -m "Merge branch 'dev'"
 
 python -B summary.py
@@ -20,8 +25,8 @@ python -B normalize_img_links.py
 
 set +e
 
-git add .
-git commit -m "Update"
+git add -A
+git commit -m Update
 git push origin master
 
-git checkout dev
+git switch dev
